#  DB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:13.16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: fakeshop
            - name: POSTGRES_USER
              value: fakeshop
            - name: POSTGRES_PASSWORD
              value: postgres123
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
    - port: 5432
      targetPort: 5432
---
# web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops4devs-fake-shop
  labels:
    app: devops4devs-fake-shop
spec:
  selector:
    matchLabels:
      app: devops4devs-fake-shop
  template:
    metadata:
      labels:
        app: devops4devs-fake-shop
    spec:
      containers:
        - name: devops4devs-fake-shop
          image: maycon8609/devops4devs-fake-shop:v2
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: postgre
            - name: DB_USER
              value: fakeshop
            - name: DB_PASSWORD
              value: postgres123
            - name: DB_NAME
              value: fakeshop
            - name: FLUSK_APP
              value: index.py
---
apiVersion: v1
kind: Service
metadata:
  name: devops4devs-fake-shop
spec:
  selector:
    app: devops4devs-fake-shop
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer